//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrewBot.Config {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigurationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigurationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrewBot.Config.ConfigurationResources", typeof(ConfigurationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to config.
        /// </summary>
        internal static string ConfigTag {
            get {
                return ResourceManager.GetString("ConfigTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to earn-rate.
        /// </summary>
        internal static string Currency_EarnRateAttribute {
            get {
                return ResourceManager.GetString("Currency_EarnRateAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to custom-name.
        /// </summary>
        internal static string Currency_NameAttribute {
            get {
                return ResourceManager.GetString("Currency_NameAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to currency.
        /// </summary>
        internal static string CurrencyTag {
            get {
                return ResourceManager.GetString("CurrencyTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gamble-interval.
        /// </summary>
        internal static string Gambling_IntervalAttribute {
            get {
                return ResourceManager.GetString("Gambling_IntervalAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minimum.
        /// </summary>
        internal static string Gambling_MinimumAmountAttribute {
            get {
                return ResourceManager.GetString("Gambling_MinimumAmountAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to odds.
        /// </summary>
        internal static string Gambling_OddsAttribute {
            get {
                return ResourceManager.GetString("Gambling_OddsAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gambling.
        /// </summary>
        internal static string GamblingTag {
            get {
                return ResourceManager.GetString("GamblingTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wait-time.
        /// </summary>
        internal static string MessageInterval_WaitTimeAttribute {
            get {
                return ResourceManager.GetString("MessageInterval_WaitTimeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interval.
        /// </summary>
        internal static string MessageIntervalTag {
            get {
                return ResourceManager.GetString("MessageIntervalTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to messages.
        /// </summary>
        internal static string MessagesTag {
            get {
                return ResourceManager.GetString("MessagesTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message.
        /// </summary>
        internal static string MessageTag {
            get {
                return ResourceManager.GetString("MessageTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to banned-words.
        /// </summary>
        internal static string Moderation_BannedWordsTag {
            get {
                return ResourceManager.GetString("Moderation_BannedWordsTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timeout-time.
        /// </summary>
        internal static string Moderation_TimeoutTimeAttribute {
            get {
                return ResourceManager.GetString("Moderation_TimeoutTimeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timeout-words.
        /// </summary>
        internal static string Moderation_TimeoutWordsTag {
            get {
                return ResourceManager.GetString("Moderation_TimeoutWordsTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to word.
        /// </summary>
        internal static string Moderation_WordSubtag {
            get {
                return ResourceManager.GetString("Moderation_WordSubtag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moderation.
        /// </summary>
        internal static string ModerationTag {
            get {
                return ResourceManager.GetString("ModerationTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        internal static string Subscriber_TitleAttribute {
            get {
                return ResourceManager.GetString("Subscriber_TitleAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscribers.
        /// </summary>
        internal static string SubscribersTag {
            get {
                return ResourceManager.GetString("SubscribersTag", resourceCulture);
            }
        }
    }
}
